### ISSUE TITLE
Local variable 'tmp_app_files' referenced before assignment when installing Ultima

### ISSUE THREAD

**Issue by ghost** [yancharkin/games_nebula#43]
---

**System:**
 - Distro: Fedora 29
 - gtk3 version: 3.24.1
 - python version 2.7.15 and 3.7.3
 - lgogdownloader version 3.5.d85d931
 - innoextract version 1.7
 - DE or WM KDE
 - DM SDDM

**Bug description**
Local variable 'tmp_app_files' referenced before assignment when installing Ultima.

Full traceback

```
Done with 1 error and 8 warnings.
Traceback (most recent call last):
  File "./games_nebula.py", line 5488, in watch_process
    self.goglib_install_game(game_name)
  File "./games_nebula.py", line 5223, in goglib_install_game
    files_to_move = tmp_app_files
UnboundLocalError: local variable 'tmp_app_files' referenced before assignment
```

**Steps to reproduce the behavior**
Install the original Ultima, get the crash. Ultima is the only game I've observed the issue on so far, but it happens every time.

**Comment by ghost** [comment]
This also happens on Ultima 2, Ultima 3, Ultimate DOOM, System Shock Enhanced, and I'm sure some others. So far it just seems to be DOS games, but only *some* DOS games. Dark Forces installed without issue.

**Comment by ghost** [comment]
I created the directory manually and the installation "succeeded", but GN never actually ran the installer

**Comment by ghost** [comment]
It looks like GN is looking for a directory structure that just... doesn't exist. This may be an issue with lgogdownloader, I'll try an older version.

**Comment by yancharkin** [comment]
Looks like those games packed with a newer version of Inno Setup. innoextract (that used by GN for unpacking installers) currently supports installers created by Inno Setup 1.2.10 to 5.6.0. When trying to unpack 'System Shock Enhanced Edition' with it, I got: 'Warning: Unexpected setup data version: 5.6.2'. I'm almost sure that's the case with the other games, but it will be nice if you check (I don't own any of those games):

    innoextract --gog <setup_file.exe>

**Comment by ghost** [comment]
```
λ innoextract --gog setup_ultima_1.0_cs_\(28189\).exe 
Warning: Unexpected setup data version: 5.6.2 (unicode)
Warning: Unexpected Auto Boolean value: 19
Warning: Unexpected Auto Boolean value: 20
Warning: Unexpected trailing byte in UTF-16 string.
Warning: Unexpected data while converting from UTF-16LE to UTF-8.
Warning: Unexpected trailing byte in UTF-16 string.
Warning: Unexpected data while converting from UTF-16LE to UTF-8.
Warning: Unexpected data while converting from UTF-16LE to UTF-8.
Stream error while parsing setup headers!
 ├─ detected setup version: 5.6.2 (unicode)
 └─ error reason: basic_ios::clear: iostream error
If you are sure the setup file is not corrupted, consider 
filing a bug report at http://innoextract.constexpr.org/issues
Done with 1 error and 8 warnings.
```

Alright, looks like I'll file a bug report with innoextract.

Thanks for the help!

**Comment by yancharkin** [comment]
It seems it's already fixed: https://github.com/dscharrer/innoextract/issues/74

**Comment by ghost** [comment]
Yup, just compiled innoextract@HEAD and it works fine.

Thanks again!

**Comment by yancharkin** [comment]
You are welcome.

**Comment by ghost** [comment]
Hmmm, just tried actually installing from GN and now I get a new traceback:

```
mv: cannot stat '/home/tay/.games_nebula/games/goglib/installed/ultima_1/game/app//*_single.conf': No such file or directory
Traceback (most recent call last):
  File "./games_nebula.py", line 5488, in watch_process
    self.goglib_install_game(game_name)
  File "./games_nebula.py", line 5285, in goglib_install_game
    update_conf_file(game_dir + '/dosbox_game.conf')
  File "./games_nebula.py", line 5250, in update_conf_file
    file_to_change = open(file_path, 'r')
IOError: [Errno 2] No such file or directory: '/home/tay/.games_nebula/games/goglib/installed/ultima_1/dosbox_game.conf'
```

So it looks like it isn't *just* an innoextract issue

**Comment by yancharkin** [comment]
Can you unpack installer with innoextact and tell me the content of the 'app' directory?

**Comment by ghost** [comment]
```
λ ls app
goggame-1207662593.ico  webcache.zip

λ tree .
.
├── app
│   ├── goggame-1207662593.ico
│   └── webcache.zip
├── CASTLE.16
├── CASTLE.4
├── CGAFIGHT.BIN
├── CGAMOND.BIN
├── CGASPACE.BIN
├── CGATILES.BIN
├── CGATOWN.BIN
├── commonappdata
│   └── GOG.com
│       └── supportInstaller
│           └── uninstall.dll
├── DOSBOX
│   ├── Documentation
│   │   ├── AUTHORS.txt
│   │   ├── COPYING.txt
│   │   ├── INSTALL.txt
│   │   ├── NEWS.txt
│   │   ├── README.txt
│   │   └── THANKS.txt
│   ├── dosbox-0.74-2.1.tar.gz
│   ├── DOSBox 0.74-2 Manual.txt
│   ├── DOSBox.exe
│   ├── GOGDOSConfig.exe
│   ├── SDL.dll
│   ├── SDL_net.dll
│   └── Video Codec
│       ├── Video Instructions.txt
│       ├── zmbv.dll
│       └── zmbv.inf
├── EGAFIGHT.BIN
├── EGAMOND.BIN
├── EGASPACE.BIN
├── EGATILES.BIN
├── EGATOWN.BIN
├── GEN.EXE
├── goggame-1207662593.hashdb
├── goggame-1207662593.info
├── goggame-1207662593.script
├── MAP.BIN
├── MONDAIN.EXE
├── NIF.BIN
├── OUT.EXE
├── __redist
│   └── ISI
│       └── scriptinterpreter.exe
├── setup_ultima_1.0_cs_(28189).exe
├── SPACE.EXE
├── __support
│   └── app
│       ├── dosboxULTIMA1.conf
│       └── dosboxULTIMA1_single.conf
├── T1KFIGHT.BIN
├── T1KMOND.BIN
├── T1KSPACE.BIN
├── T1KTILES.BIN
├── T1KTOWN.BIN
├── TCD.BIN
├── tmp
│   ├── 1207658651_brazilian.jpg
│   ├── 1207658651_chinese.jpg
│   ├── 1207658651_english.jpg
│   ├── 1207658651_french.jpg
│   ├── 1207658651_german.jpg
│   ├── 1207658651_polish.jpg
│   ├── 1207658651_russian.jpg
│   ├── 1457950224_brazilian.jpg
│   ├── 1457950224_chinese.jpg
│   ├── 1457950224_english.jpg
│   ├── 1457950224_french.jpg
│   ├── 1457950224_german.jpg
│   ├── 1457950224_polish.jpg
│   ├── 1457950224_russian.jpg
│   ├── background.jpg
│   ├── background.png
│   ├── bg-bot@2x.jpg
│   ├── BigFail200.png
│   ├── BigFail.png
│   ├── BigOK200.png
│   ├── BigOK.png
│   ├── BigWarn200.png
│   ├── BigWarn.png
│   ├── bottombar200.png
│   ├── bottombar.png
│   ├── botva2.dll
│   ├── btn_browse200.png
│   ├── btn_browse.png
│   ├── btn_close200.png
│   ├── btn_close.png
│   ├── btn_continue200.png
│   ├── btn_continue.png
│   ├── btn_exit200.png
│   ├── btn_exit.png
│   ├── btn_launch200.png
│   ├── btn_launch.png
│   ├── btn_md5200.png
│   ├── btn_md5.png
│   ├── btn_options200.png
│   ├── btn_options.png
│   ├── btn_save_as200.png
│   ├── btn_save_as.png
│   ├── btn_skip200.png
│   ├── btn_skip.png
│   ├── btn_start200.png
│   ├── btn_start.png
│   ├── btn_tryagain200.png
│   ├── btn_tryagain.png
│   ├── crcdll.dll
│   ├── empty
│   ├── error200.png
│   ├── error_icon200.png
│   ├── error_icon.png
│   ├── error.png
│   ├── EULA200.png
│   ├── EULAAccepted200.png
│   ├── EULAAccepted.png
│   ├── EULA_bkg.png
│   ├── EULA_de-DE.txt
│   ├── EULA_en-US.txt
│   ├── EULA_fr-FR.txt
│   ├── EULA_pl-PL.txt
│   ├── EULA.png
│   ├── EULA_pt-BR.txt
│   ├── EULA_ru-RU.txt
│   ├── EULAShow200.png
│   ├── EULAShow.png
│   ├── EULA.txt
│   ├── EULA_zh-Hans.txt
│   ├── GOG200_new.png
│   ├── GOG200.png
│   ├── gog.ico
│   ├── gog_installer_background.jpg
│   ├── gog_new.png
│   ├── GOG.png
│   ├── InnoCallback.dll
│   ├── innoSetupEula.txt
│   ├── md5log.ini
│   ├── ok200.png
│   ├── ok.png
│   ├── OpenSans-Regular.ttf
│   ├── OpenSans-Semibold.ttf
│   ├── progress_center200.png
│   ├── progress_center.png
│   ├── progress_left200.png
│   ├── progress_left.png
│   ├── progress_right200.png
│   ├── progress_right.png
│   ├── scroll-handle-bot.png
│   ├── scroll-handle-top.png
│   ├── slideshow.ini
│   ├── Support.ico
│   ├── trackbar_back200.png
│   ├── trackbar_back.png
│   ├── trackbar_btn200.png
│   ├── trackbar_btn.png
│   ├── track_center200.png
│   ├── track_center.png
│   ├── track_left200.png
│   ├── track_left.png
│   ├── track_right200.png
│   └── track_right.png
├── Ultima_1_manual.pdf
└── ULTIMA.EXE

12 directories, 153 files
```

**Comment by yancharkin** [comment]
GOG changed the way they package their installers. I made some changes, hopefully, now GN should work fine.

**Comment by ghost** [comment]
Fantastic, thank you so much!

Every game I mentioned not working now installs and runs fine, so it looks like that definitely fixed it :)
