### ISSUE TITLE
"No such file or directory" error on start

### ISSUE THREAD

**Issue by Ezwen** [yancharkin/games_nebula#7]
On Fedora 27, after having installed all dependencies (`sudo dnf install xterm curl tar p7zip p7zip-plugins cabextract unshield megatools wine winetricks dosbox scummvm`), I encounter the following error when starting games nebula:
~~~
$ ./start.sh
Traceback (most recent call last):
  File "/home/zerwan/Applications/games_nebula/games_nebula.py", line 6931, in <module>
    sys.exit(main())
  File "/home/zerwan/Applications/games_nebula/games_nebula.py", line 6927, in main
    app = GUI()
  File "/home/zerwan/Applications/games_nebula/games_nebula.py", line 131, in __init__
    self.goglib_authorized = goglib_check_authorization.goglib_authorized()
  File "/home/zerwan/Applications/games_nebula/modules/goglib_check_authorization.py", line 7, in goglib_authorized
    stdin=subprocess.PIPE, stderr=subprocess.STDOUT)
  File "/usr/lib64/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1025, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
~~~

**Comment by Ezwen** [comment]
Oh wait, I misread the README. I forgot to compile and install lgogdownloader. I'll try that!

If by any chance there could be more informative error messages, that could be a possible improvement :).

**Comment by Ezwen** [comment]
I do not encounter this problem anymore with lgogdownloader installed, sorry for the report
